# Backup location to teleport prisoner on unjail if location before jailed is found corrupt.
backupLocation:
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Counts offline time as sentence time.
offlineTime: false

# Why would you even do this.
jailEvenIfTheUserNeverJoinedTheServerBefore: false

# Time after which the player will be released if they don't join the server in said time.
# Set to 0 to disable.
#discardDataAfter: 7
# To-be-implemented.

# Change prisoner group when jailed.
# Needs LuckPerms (preferred) or Vault to be installed.
changeGroup: false
# Group name for prisoner to be moved to when jailed.
prisonerGroup: prisoner

# Automatically save prisoners and jails data files.
# Set to 0 to disable.
autoSaveTimeInMinutes: 5

# Tells the plugin to use a MySQL database to store the data.
# If set to false, the data will be stored in YAML files.
#useMySQL: false
# If set to true, you'll need to provide the connection credentials.
#mysql:
#  host: 127.0.0.1
#  port: 3306
#  schema: betterjails
#  user: root
#  passwd: root
#  tablePrefix: bj_
# To-be-implemented.

# Messages shown.
# All messages will follow the short plugin prefix.
messages:
  # Placeholders for /jail:
  # · {prisoner}: player to be jailed.
  # · {player}: player that executes the command.
  # · {jail}: jail name to where the prisoner will be sent.
  # · {time}: time argument provided.
  jailTempSuccess: "&a{prisoner} &bhas been jailed by &a{player} &bfor &2{time}&b."
  jailPermaSuccess: "&a{prisoner} &bhas been jailed by &a{player} &bfor a &oreally &blong time."
  jailFailedPlayerNeverJoined: "&bPlayer &a{prisoner} &bnever joined this server."
  jailFailedPlayerExempt: "&a{prisoner} &bcannot be jailed."
  jailFailedJailNotFound: "&bJail &e{jail} &bnot found."
  jailFailedTimeIncorrect: "&bThe time provided is not valid."

  # Placeholders for /jail info:
  # · {prisoner}: player to retrieve the status and info.
  # · {player}: player that executes the command.
  infoFailedPlayerNotJailed: "&bThe player you are requesting the information from is not currently serving a sentence."
  infoFailedPlayerNeverJoined: "&bPlayer &a{prisoner} &bnever joined this server."

  # Placeholders for /unjail:
  # · {prisoner}: player to be unjailed.
  # · {player}: player that executes the command.
  unjailSuccess: "&a{prisoner} &bhas been unjailed by &a{player}&b."
  unjailFailedPlayerNotJailed: "&a{prisoner} &bcould not be unjailed, player wasn't jailed."
  unjailFailedPlayerNeverJoined: "&bPlayer &a{prisoner} &bnever joined this server."

  # Placeholders for /setjail and /deljail:
  # · {player}: player that executes the command.
  # · {jail}: jail name to be added/removed.
  setjailFromConsole: "&bOnly players can set jails!"
  setjailSuccess: "&bJail added successfully!"
  deljailSuccess: "&bJail removed successfully!"
  deljailFailed: "&bThat jail does not exist!"

  # Placeholders for /betterjails reload and /betterjails save:
  # · {player}: player that executes the command.
  reload: "&6Files reloaded successfully!"
  save: "&6Files saved successfully!"

  # Placeholders for /jails premessages:
  # · None :(
  listNoJails: "&bThere are no jails available!"
  listJailsPremessage: "&bAvailable jails:"

  # Placeholders for /jails list:
  # · None :(
  jailsListingStyle: "line"
  jailsListingColor: "&a"   # Must be a valid color/format code.
  jailsListingSeparators:
    list: "· "
    line: ", "

  # jailsListingStyle can be any of these values:
  # · list
  # · line
  #
  # Examples with default separators:
  #   list:
  #     · jail1
  #     · jail2
  #     · jail3
  #   line:
  #     jail1, jail2, jail3
