name: BetterJails
authors: [ Fefo6644 ]
version: ${project.version}
main: ar.fefo.betterjails.Main
api-version: "1.13"
load: POSTWORLD
softdepend: [ Essentials, Vault, PlaceholderAPI ]

permissions:
  betterjails.admin:
    default: false
    children:
      betterjails.jail: true
      betterjails.jail.exempt: true
      betterjails.jails: true
      betterjails.unjail: true
      betterjails.setjail: true
      betterjails.deljail: true
      betterjails.receivebroadcast: true
      betterjails.betterjails: true
      betterjails.betterjails.reload: true
      betterjails.betterjails.save: true
  betterjails.moderator:
    default: false
    children:
      betterjails.jail: true
      betterjails.jail.exempt: true
      betterjails.jails: true
      betterjails.unjail: true
      betterjails.setjail: false
      betterjails.deljail: false
      betterjails.receivebroadcast: true
      betterjails.betterjails: true
      betterjails.betterjails.reload: false
      betterjails.betterjails.save: false
  betterjails.jail:
    default: op
  betterjails.jail.exempt:
    default: op
  betterjails.jails:
    default: op
  betterjails.unjail:
    default: op
  betterjails.setjail:
    default: op
  betterjails.deljail:
    default: op
  betterjails.receivebroadcast:
    default: op
  betterjails.betterjails:
    default: true
  betterjails.betterjails.reload:
    default: op
  betterjails.betterjails.save:
    default: op

commands:
  jail:
    permission: betterjails.jail
    permission-message: "§cYou cannot execute this command"
    usage: "§cUsage: /jail <player> <jail> <time>\n§cUsage: /jail info <player>"
    description: Sends a player to the provided jail, and won't be teleported back until they spend online the time provided.
  jails:
    permission: betterjails.jails
    permission-message: "§cYou cannot execute this command"
    usage: "§cUsage: /jails"
    description: Prints a list of available jails.
  unjail:
    permission: betterjails.unjail
    permission-message: "§cYou cannot execute this command"
    usage: "§cUsage: /unjail <player>"
    description: Teleports a jailed player back to where they were when jailed.
  setjail:
    permission: betterjails.setjail
    permission-message: "§cYou cannot execute this command"
    usage: "§cUsage: /setjail <jailname>"
    description: Adds a new jail location in where the command is executed.
  deljail:
    permission: betterjails.deljail
    permission-message: "§cYou cannot execute this command"
    usage: "§cUsage: /deljail <jailname>"
    description: Removes a jail location from the jails list.
  betterjails:
    permission: betterjails.betterjails
    permission-message: "§cYou cannot execute this command"
    description: Prints the version of the plugin.
